void printResults(char* function, int passed, int failed);
void testHeaders();
void testRead();
void testWrite();
void testBinWrite();
void testCompare();
void testReadBin();
void testa2b();
void testb2a();
void testReduceSize();
void testSubImage();
void testInsert();
void testEmpty();
